# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
      
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'testing'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./ 
      run: yarn
    - name: build client 
      working-directory: ./
      run: yarn run build
  docs:
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'testing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./
          recurse: true
          output_dir: ./docs
          front_page: README.md
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: docs
          publish_dir: ./
